---
layout: cv
title: Elizabeth Hunter's CV
---
# Elizabeth Hunter
Broadcast Engineer, Software Engineering Student

<div id="webaddress">
<a href="lizziehun13@gmail.com">lizziehun13@gmail.com </a>
| <a href="linkedin.com/in/elizabeth-hunter-0649291a7">My Linkedin page</a>
</div>

##### Currently

Working as Broadcast Engineer

##### Specialized in

Embedded Systems and Electrical Engineering

##### Research interests

Data Science, App Development, Electrical Engerineering

## Education

`September 2018 - Now`
__Brigham Young University-Idaho__

- Software Engineering: Embedded Systemes

## Experience

`August 2022 - April 2023`
__Media Systems Engineer | AV & Broadcast Productions | Rexburg, Idaho__	
- Trained 3 new hires on weekly event set up and equipment use
- Wrote 4 AWS lambda functions for AWS Media Live streaming channels
- Programmed 2 scripts to simplify tasks; automated stream management and stream user statistics data analysis
- Updated firmware and software on over 15 different types of equipment

`July 2021 - August 2022`
__Video Engineer Tech | AV & Broadcast Productions | Rexburg, Idaho__
- Maintained, set up, organized, and taught new hires procedures for over 15 cameras and various other equipment
- Customized equipment for over 3 sister departments and troubleshot any issues
- Controlled Iris for around 5 cameras per event
- Redesigned and implemented design for 1 building's signal router 


<!-- ### Footer

Last updated: April 2024 -->